name: PR Agent Workflow
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
permissions:
  issues: write
  pull-requests: write
  contents: write
jobs:
  pr_agent_job:
    # Run for Atmos component updates
    if: ${{ github.event.sender.login != 'renovate[bot]' }}
    runs-on: [self-hosted, Ubuntu, Common]
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
