name: Test Sweeper

# This GitHub action periodically sweeps the tenant for dangling resources.
# Optionally, you can manually run this workflow from the Actions tab.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Once a day

permissions:
  contents: read

jobs:
  sweep:
    name: Sweep
    concurrency:
     group: sweep-${{ github.ref }}
     cancel-in-progress: false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Block egress)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
          cache: true
        id: go
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
        with:
          version: "3.x"
      - run: go mod download
      - name: Sweep Dangling Resources
        env:
          ARMIS_API_URL: ${{ secrets.ARMIS_API_URL }}
          ARMIS_API_KEY: ${{ secrets.ARMIS_API_KEY }}
        run: task sweep
