name: Validate Codeowners
on:
  workflow_dispatch:

  pull_request:

permissions:
  contents: read

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Block egress)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          objects.githubusercontent.com:443
          codeload.github.com:443
          raw.githubusercontent.com:443
          release-assets.githubusercontent.com:443

    - name: "Checkout source code at current commit"
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: step-security/codeowners-validator@073378e2c16714d69ac00356acebdb7505d82c7e # v0.7.4
      if: github.event.pull_request.head.repo.full_name == github.repository
      name: "Full check of CODEOWNERS"
      with:
        # For now, remove "files" check to allow CODEOWNERS to specify non-existent
        # files so we can use the same CODEOWNERS file for Terraform and non-Terraform repos
        #   checks: "files,syntax,owners,duppatterns"
        # TODO Restore owners check once access token with appropriate permissions is available
        #checks: "syntax,owners,duppatterns"
        checks: "syntax,duppatterns"
        # GitHub access token is required only if the `owners` check is enabled
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: step-security/codeowners-validator@073378e2c16714d69ac00356acebdb7505d82c7e # v0.7.4
      if: github.event.pull_request.head.repo.full_name != github.repository
      name: "Syntax check of CODEOWNERS"
      with:
        checks: "syntax,duppatterns"
